dataset:
  raw_path: "./dataset/raw"
  processed_path: "./dataset/processed"
  
  classes:
    horse: 6
    penguin: 7
    pig: 8
    
  raw_structure: 
    gt_dir: "gt"
    gt_ext: ".txt"
    video_dir: "videos"
    video_ext: ".mp4"

models:
  efficientdet:
    path: "./models/efficientdet"

training:
  img_size: 640
  batch_size: 16
  epochs: 100